### ISSUE TITLE
FAQ page : unnecessary horizontal line is occuring in chrome, Opera and IE9

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Central-Wheatbelt-Imports#11]
![2015-11-05_1056](https://cloud.githubusercontent.com/assets/13309806/10964225/7d2ca604-835a-11e5-8254-5820041636a2.png)

**Comment by ravititan** [comment]
I have tested in Chrome,IE,Opera. Please check the screenshot of Chrome.
![faq-issue](https://cloud.githubusercontent.com/assets/13450891/11366040/ac049f1a-92d0-11e5-909a-15978cb21b7c.jpg)

**Comment by ravi-josyula** [comment]
Still bug is not fixed in IE9
