### ISSUE TITLE
Contact Us page : Placeholders are getting clipped in Chrome, Opera and IE9

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Central-Wheatbelt-Imports#13]
![2015-11-05_1149](https://cloud.githubusercontent.com/assets/13309806/10964267/f215d936-835a-11e5-821a-b06117d25f4a.png)

**Comment by ravititan** [comment]
Tested in all the browsers (IE9,Opera,Chrome,Mozilla)

**Comment by ravi-josyula** [comment]
When I'm testing it is a bug, but now it is fixed
