### ISSUE TITLE
Header Section: Search layout is getting distorted

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Central-Wheatbelt-Imports#19]
![2015-11-05_1708](https://cloud.githubusercontent.com/assets/13309806/10991576/4c877150-8413-11e5-82ba-02fa9993a29d.png)

**Comment by ravititan** [comment]
Tested in browsers the search button is fine.

**Comment by ravi-josyula** [comment]
Still bug is not fixed in IE9 and Safari
![2015-12-01_1622](https://cloud.githubusercontent.com/assets/13309806/11498725/1b76a942-97d6-11e5-9814-5de4b7a37d92.png)
![2015-12-01_1622_001](https://cloud.githubusercontent.com/assets/13309806/11498730/1f3af7e0-97d6-11e5-823c-f13ff2b2178b.png)
