### ISSUE TITLE
Product Range single page : Enquire now button should link to Contact Us page

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Central-Wheatbelt-Imports#20]
![four camera 7in wireless monitors copy - central wheatbelt imports 2015-11-06 10-21-20](https://cloud.githubusercontent.com/assets/13309806/10991641/c7e0efb6-8413-11e5-9cf9-5cb312ee7511.png)

**Comment by ravititan** [comment]
Its a page link user need to select a page to link.
