### ISSUE TITLE
Contact us page : Input text is out of scope in Safari

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Central-Wheatbelt-Imports#44]
![2015-11-05_1152](https://cloud.githubusercontent.com/assets/13309806/10993128/5884e074-8421-11e5-8552-47a49214e5e5.png)

**Comment by ravititan** [comment]
Tested in safari and the input text is fine.
![safari-input-issue](https://cloud.githubusercontent.com/assets/13450891/11361116/d160661a-92b0-11e5-8f98-ad705a745d64.jpg)

**Comment by ravi-josyula** [comment]
when I'm testing it is bug, but now it is fixed
