### ISSUE TITLE
Cart page(Billing details) : Titles are getting clipped in all browsers except mozilla

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Central-Wheatbelt-Imports#49]
![2015-11-09_1023](https://cloud.githubusercontent.com/assets/13309806/11027070/6fc8e626-8666-11e5-8b72-262bfccec787.png)

**Comment by ravititan** [comment]
I have checked the Billing details form in all the browser (Chrome,Safari,Opera,Mozilla )and titles are not getting clipped.
